version: "3"
services:
  server:
    # replace username/repo:tag with your name and image details
    image: goyalshubham13/todo-backend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:3000"
    networks:
      - webnet
  client:
    # replace username/repo:tag with your name and image details
    image: goyalshubham13/todo-frontend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8081:3001"
    networks:
      - webnet
networks:
  webnet: